version: "3"

services:
    back:
        container_name: prices_calc_api
        build: back/
        command: dotnet /app/VmsInformWeb.dll
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:8800
        ports:
            - 6578:8800
        networks:
            - frontend
            - backend
            - default
        
        volumes:
            - ./back/Sources/VmsInformWeb/appsettings.json:/app/appsettings.json
            
    front:
        build: front/
        #network_mode: "host"
        depends_on:
            - back
        ports:
            - 8081:8081
        
        volumes:
            - ./log/nginx:/var/log/nginx
        
        networks:
            - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge